### ISSUE TITLE
installation of extra package needed

### ISSUE THREAD

**Issue by maxbre** [UBESP-DCTV/imthcm#5]
install.packages("docopt")

by running the module 'hm.R' 'from CL I got a message that an additional package installation was needed (after that the whole process of installing the package imthcm into R went apparently fine)

check dependencies in the installation phase?

I managed to run the modules after installing the needed package "docopt" 
(it's just an annoyance rather than a real bug, but probably worth fixing it)

keep on going with the good work, compliments!

bye 

max

**Comment by CorradoL** [comment]
The package `docopt` is needed to run `hm.R` and `cm.R` by command line on Linux. Those files are included in the repo (and in the folder `/modules` after installing the package, i.e., `system.file('modules', 'hm.R', package = 'imthcm')`) to find them easily by the IMT staff. But they are not a proper part of it, and so `docopt`.

I add it to the suggested package. It will be installed, among the other, unnecessary to imthcm standard usage (e.g. run the test of the package), by `devtools::install_github("UBESP-DVTV/imthcm", dependencies = TRUE)`.

**Comment by maxbre** [comment]
fine, see you soon
bye
max
