### ISSUE TITLE
update help text on predict_hm()

### ISSUE THREAD

**Issue by maxbre** [UBESP-DCTV/imthcm#8]
update help text on predict_hm()

A data frame with weather historical data with number of rows equal to the lenght of health_events_history

**Comment by CorradoLanera** [comment]
I don't understand this issue.

**Comment by maxbre** [comment]
I think to remember it's a trivial copy and paste problem with the text of the function train_event_models()
" .....with number of rows equal to the lenght of  \code{health_events_history} "

it does not seems to me that is always necessary true with the predict_hm()  function

am I wrong?

for someone reading the help of the function might be misleading (it was for myself)

bye

**Comment by CorradoLanera** [comment]
Fixed; the update documentation will be available from the next release. Thanks.
