### ISSUE TITLE
warning message

### ISSUE THREAD

**Issue by maxbre** [UBESP-DCTV/imthcm#9]
memo, to have look into it

there is a warning message when predict() 

###
predict_hm(
   
    default_models,  # default models
   
    weather_history =  thes, # actual data
   
    weather_today   =  thes[-(1:3), ] # excluding first 3 days for the time lag -3d
   
    ) 

Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Joining, by = c("date", "pm25", "no2", "temp_mean", "pm10", "press_bar_mean")
Adding missing grouping variables: `group_date`
Warning messages:
1: `.key` is deprecated
2: `cols` is now required.
Please use `cols = c(today_data)`
###

**Comment by CorradoLanera** [comment]
Fixed; moreover, I removed all the (annoying) join messages too.
The fix will appear starting from the next release.
